### ISSUE TITLE
App crashes (Seen in Crashlytics)

### ISSUE THREAD

**Issue by yosikal** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1032]
Crashlytics shows the following error:

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.BaseBundle.get(java.lang.String)' on a null object reference
       at nl.xservices.plugins.ShareChooserPendingIntent.onReceive(ShareChooserPendingIntent.java:12)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2579)
       at android.app.ActivityThread.access$1700(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by EddyVerbruggen** [comment]
I'll add a little guard around that code.

**Comment by EddyVerbruggen** [comment]
FIx is now on npm, version 5.4.6.
