### ISSUE TITLE
App crash on Android

### ISSUE THREAD

**Issue by gatelli** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#1140]
I have a runtime error when running sharing on Android (working on iOS):

java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at nl.xservices.plugins.SocialSharing$2.run(SocialSharing.java:334)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

Does it means something for you ?

**Comment by EddyVerbruggen** [comment]
How is the plugin invoked to produce this crash?

**Comment by gatelli** [comment]
I'm sorry I found a typo in appPackageName which was probably leading to this error.

**Comment by yogeshjuyal** [comment]
@gatelli help my same issue with Android  11

working with other phones

**Comment by gatelli** [comment]
I'm sorry I can't remember but as I said it was an error with my appPackageName

**Comment by flastowizka** [comment]
The version 6.0.3 the problem occurred yet.

I just install version from github and the problem was fix and works fine.
