### ISSUE TITLE
Cannot Build on Cordova 4.2.0

### ISSUE THREAD

**Issue by fsbatista** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#299]
When I try to build the app, after doing the install, I get the following msg:

``` sh
The following build commands failed:
    CompileC build/side.build/Debug-iphonesimulator/side.build/Objects-normal/i386/SocialSharing.o side/Plugins/nl.x-services.plugins.socialsharing/SocialSharing.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: /PATH/Ionic Examples/side/platforms/ios/cordova/run: Command failed with exit code 65
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

Thoughts?

**Comment by fsbatista** [comment]
The problem was with Ionic/Cordova Build. It wasn't copying the plugin files to the specific ios build. All good now.

**Comment by calendee** [comment]
@fsbatista Having the same problem with Ionic/Cordova.  How did you resolve this?

**Comment by calendee** [comment]
Some additional info:

I faced this same problem with a new Android app after installiing via CLI.  After removing the plugin and re-adding version 4.3.12 ( `cordova plugin add https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin#81c25f57e27edfbb5bef9709c845bc29c6e3179b` ), plugin works perfectly in Android.

For iOS, Version 4.3.12 works great on an app that never had 4.3.13.  However, on an app that I installed 4.3.13 from scratch, I can't revert to 4.3.12 as I did with Android.  

I'm still getting : 
```
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/jn/Android-SDK/sdk/tools:/Users/jn/Android-SDK/sdk/platform-tools:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/git/bin:/Users/jn:/usr/local/jq:/usr/share/ant/bin:/usr/local/nginx:/usr/local/nginx/sbin:/Users/jn/.rvm/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk -L/Users/jn/Documents/Apps/smartWorx/platforms/ios/build/emulator -LABBYYMobileOCR/Lib/iPhoneSimulator -LABBYYMobileImaging/Lib/Release-iphonesimulator -F/Users/jn/Documents/Apps/smartWorx/platforms/ios/build/emulator -filelist /Users/jn/Documents/Apps/smartWorx/platforms/ios/build/SmartWorx.build/Debug-iphonesimulator/SmartWorx.build/Objects-normal/i386/SmartWorx.LinkFileList -Xlinker -objc_abi_version -Xlinker 2 -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -force_load /Users/jn/Documents/Apps/smartWorx/platforms/ios/build/emulator/libCordova.a -lAbbyyMsdk -lMobileImagingEngine -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=6.0 -framework CoreLocation -framework ImageIO /Users/jn/Documents/Apps/smartWorx/platforms/ios/build/emulator/libCordova.a -framework QuartzCore -framework AssetsLibrary -framework CoreGraphics -framework MobileCoreServices -lstdc++.6 -weak_framework SystemConfiguration -Xlinker -dependency_info -Xlinker /Users/jn/Documents/Apps/smartWorx/platforms/ios/build/SmartWorx.build/Debug-iphonesimulator/SmartWorx.build/Objects-normal/i386/SmartWorx_dependency_info.dat -o /Users/jn/Documents/Apps/smartWorx/platforms/ios/build/emulator/SmartWorx.app/SmartWorx
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_MFMailComposeViewController", referenced from:
      objc-class-ref in SocialSharing.o
  "_OBJC_CLASS_$_MFMessageComposeViewController", referenced from:
      objc-class-ref in SocialSharing.o
  "_OBJC_CLASS_$_SLComposeViewController", referenced from:
      objc-class-ref in SocialSharing.o
  "_SLServiceTypeFacebook", referenced from:
      -[SocialSharing shareViaFacebook:] in SocialSharing.o
      -[SocialSharing shareViaFacebookWithPasteMessageHint:] in SocialSharing.o
      -[SocialSharing isAvailableForSharing:type:] in SocialSharing.o
  "_SLServiceTypeSinaWeibo", referenced from:
      -[SocialSharing isAvailableForSharing:type:] in SocialSharing.o
  "_SLServiceTypeTencentWeibo", referenced from:
      -[SocialSharing isAvailableForSharing:type:] in SocialSharing.o
  "_SLServiceTypeTwitter", referenced from:
      -[SocialSharing shareViaTwitter:] in SocialSharing.o
      -[SocialSharing isAvailableForSharing:type:] in SocialSharing.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld build/emulator/SmartWorx.app/SmartWorx normal i386
(1 failure)
ERROR building one of the platforms: Error: /Users/jn/Documents/Apps/smartWorx/platforms/ios/cordova/build: Command failed with exit code 65
You may not have the required environment or OS to build this project
```

**Comment by fsbatista** [comment]
I had to copy the files from the root plugin dir to the ios platform plugin dir. That solved the build issue but I still can't get it to work properly.

**Comment by calendee** [comment]
So, here's my "fix" for this.

- Install 4.3.12 instead of 4.3.13
```
cordova plugin add https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin#81c25f57e27edfbb5bef9709c845bc29c6e3179b
```

- Perform the cordova build from the command line (it will fail)
```
cordova build ios
```

- Add the `Social.framework` and `MessageUI.framework` to Xcode : Build Phases -> Link Binary With Libraries as described in README.

- Build in Xcode one time
- Now, can successfully use plugin and build from command line

**Comment by rupertbear** [comment]
If anyone else ends up here then removing and adding the ios platform back again fixed this for me (and often does when weird stuff like this happens!)
