### ISSUE TITLE
Impossible to install from CLI

### ISSUE THREAD

**Issue by panurge-ws** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#316]
running 
cordova plugin add nl.x-services.plugins.socialsharing
or
cordova plugin add https://github.com/dyVerbruggen/SocialSharing-PhoneGap-Plugin.git

I got this:

Fetching plugin "nl.x-services.plugins.socialsharing" via plugin registry
SyntaxError: Unexpected token <
    at Object.parse (native)
    at Object.get_platform_json (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/config-changes.js:461:31)
    at isPluginInstalled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:247:42)
    at runInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:271:9)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:81:16
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:810:14
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)

**Comment by EddyVerbruggen** [comment]
Can you perhaps try updating your cordova / plugman npm modules? I just tried this on my Mac and it worked fine (on a brand new CLI project):

```
localhost:socialsharingcrap eddyverbruggen$ cordova plugin add nl.x-services.plugins.socialsharing
Fetching plugin "nl.x-services.plugins.socialsharing" via plugin registry
npm http GET http://registry.cordova.io/nl.x-services.plugins.socialsharing
npm http 200 http://registry.cordova.io/nl.x-services.plugins.socialsharing
Installing "nl.x-services.plugins.socialsharing" for android
Installing "nl.x-services.plugins.socialsharing" for ios
```

**Comment by panurge-ws** [comment]
I'm running it on:
plugman@0.23.0
and
cordova@4.3.0

Results:

SyntaxError: Unexpected token <
    at Object.parse (native)
    at Function.PlatformJson.load (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/PlatformJson.js:33:21)
    at runInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:257:37)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:81:16
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:810:14
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13).

**Comment by EddyVerbruggen** [comment]
Sorry to say I can't see a plugin-specific issue here..

- Did you try it on a brand new cordova-cli project?
- Did you try other plugins?

**Comment by panurge-ws** [comment]
It's seems related to a corruption on the my local project.
I'm trying to understand if it was caused by the installation of your plugin, because, yesterday, I added a new plugin (network) and everything worked fine.
Now, trying to reinstall the same network plugin, the installation fails.

**Comment by panurge-ws** [comment]
It was a git problem related to my project.
You can close this.
Thanks (and really sorry).

**Comment by EddyVerbruggen** [comment]
No worries, thx for the feedback!
