### ISSUE TITLE
Android 5.0 crashes with java.lang.NullPointerException

### ISSUE THREAD

**Issue by msokk** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#365]
Hi,

I have a Moto X device running Lollipop 5.0, where the app crashes when trying to execute:
```javascript
window.plugins.socialsharing.share(result.message, result.title, null, url, function() {...}, function() {...});
```
and returning after successful share to Twitter, FB and some other services.

Seems like `CallbackContext` is null for some weird reason.

In HTC One M7 running 5.0, this does not happen.
Plugin is the latest from Github.

Here is the stack:
```java
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=0, data=null} 
to activity {org.teleport.teleportmobile/org.teleport.teleportmobile.MainActivity}: 
java.lang.NullPointerException: Attempt to invoke virtual method 
'void org.apache.cordova.CallbackContext.sendPluginResult(org.apache.cordova.PluginResult)' 
on a null object reference
at android.app.ActivityThread.deliverResults(ActivityThread.java:3626)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:3669)
at android.app.ActivityThread.access$1300(ActivityThread.java:148)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5312)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.sendPluginResult(org.apache.cordova.PluginResult)' on a null object reference
at nl.xservices.plugins.SocialSharing.onActivityResult(SocialSharing.java:418)
at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:101)
at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:320)
at android.app.Activity.dispatchActivityResult(Activity.java:6161)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3622)
... 10 more
```

**Comment by EddyVerbruggen** [comment]
Thanks for the elaborate issue report, really helpful!

I've just pushed a change to the master branch, hopefully this fixes your trouble. Note that in this case the callback function will not be invoked as it seems to be lost while making the trip to Twitter/Fb.

**Comment by msokk** [comment]
Great, thanks for the quick reply!

Tested on Moto X and it worked, so closing this.

**Comment by jeffthompson1971** [comment]
I see this issue right now.. same exact crash on a brand new Samsung tablet.    Where is the fix?

**Comment by yurik94** [comment]
Crashingggg :(
