### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by prateek-sparx** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#400]
Hello Eddy,

I m facing the issue with plugin,
My app crashes when i click the share button, It will open the interface which shows all the app installed on which user can share. But my app getting minimized. Its a cordova app

Using that method of sharing
window.plugins.socialsharing.share(Sh_message, null, null, Sh_link)

Thanks
Prateek

**Comment by prateek-sparx** [comment]
this issue on the Android 4.4 and above version

**Comment by tavojavi** [comment]
Hello, I can share a message, the option window popups, I choose whatsapp for example, but when I hit back in the phone to go to the App again, it crashes... in the LogCat I can see this: 

09-16 14:50:48.252  22351-22351/com.kingconf.CAN2015 E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to resume activity {com.kingconf.CAN2015/com.kingconf.CAN2015.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=0, data=null} to activity {com.kingconf.CAN2015/com.kingconf.CAN2015.MainActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2790)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2819)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2266)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=0, data=null} to activity {com.kingconf.CAN2015/com.kingconf.CAN2015.MainActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3367)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2777)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2819)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2266)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at nl.xservices.plugins.SocialSharing.onActivityResult(SocialSharing.java:401)
            at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:120)
            at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:353)
            at android.app.Activity.dispatchActivityResult(Activity.java:5322)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3363)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2777)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2819)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2266)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)

**Comment by EddyVerbruggen** [comment]
Please update to a newer version of the plugin, I've fixed this a while ago. Where do you install the plugin from?

**Comment by tavojavi** [comment]
Hi Eddy, thanks for the fast reply, I´ve installed using NPM command, a week ago, let me check if I can update it in my project and is fixed. thanks!

**Comment by tavojavi** [comment]
this is what I have:
cordova-plugin-socialsharing 4.3.81 "SocialSharing"

**Comment by EddyVerbruggen** [comment]
That npm version is nog mine: https://www.npmjs.com/~appsystem, but it is the version which has this bug :(

**Comment by tavojavi** [comment]
ohh I see, but you´re listed with the link here as creator as well... https://www.npmjs.com/package/cordova-plugin-socialsharing

should I uninstall it and install yours using:
cordova plugin add nl.x-services.plugins.socialsharing

Thanks!

**Comment by EddyVerbruggen** [comment]
Yes I am, but it's not uploaded by me so I can't update it. Trying to get a hold of the uploader but he is unresponsive :(

You're best off using `cordova plugin add https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin`

**Comment by EddyVerbruggen** [comment]
Mailed again, still no luck. I read that npm ownership disputes take up to 4 weeks which is longer than I'd like to wait.. so perhaps I'll settle for `cordova-plugin-x-socialsharing` instead. Other suggestions are welcome ;)

**Comment by EddyVerbruggen** [comment]
So, cordova-plugin-x-socialsharing it is. Grab it while it's hot!

**Comment by tavojavi** [comment]
Thanks a lot for your work!! :D

2015-09-19 16:10 GMT-03:00 Eddy Verbruggen <notifications@github.com>:
