### ISSUE TITLE
Issues with android 6 marshmellow. the new external storage permissions related 

### ISSUE THREAD

**Issue by Bnaya** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#438]
on android 6, when sharing file to messenger, instagram, slack, and more its fails with this exception:
```
10-15 01:11:36.789  2328  2923 E DatabaseUtils: Writing exception to parcel
10-15 01:11:36.789  2328  2923 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/file?limit=10 from pid=13290, uid=10084 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
10-15 01:11:36.789  2328  2923 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:605)
10-15 01:11:36.789  2328  2923 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:480)
10-15 01:11:36.789  2328  2923 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:211)
10-15 01:11:36.789  2328  2923 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
10-15 01:11:36.789  2328  2923 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:453)
10-15 01:11:36.791  2328  2339 E DatabaseUtils: Writing exception to parcel
10-15 01:11:36.791  2328  2339 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/video/thumbnails?limit=10 from pid=13290, uid=10084 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
10-15 01:11:36.791  2328  2339 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:605)
10-15 01:11:36.791  2328  2339 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:480)
10-15 01:11:36.791  2328  2339 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:211)
10-15 01:11:36.791  2328  2339 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
10-15 01:11:36.791  2328  2339 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:453)
10-15 01:11:36.791  2328  7699 E DatabaseUtils: Writing exception to parcel
10-15 01:11:36.791  2328  7699 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/thumbnails?limit=10 from pid=13290, uid=10084 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
10-15 01:11:36.791  2328  7699 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:605)
10-15 01:11:36.791  2328  7699 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:480)
10-15 01:11:36.791  2328  7699 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:211)
10-15 01:11:36.791  2328  7699 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
10-15 01:11:36.791  2328  7699 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:453)
10-15 01:11:36.802 13290 13341 E b       : failed to load recent captures
10-15 01:11:36.802 13290 13341 E b       : java.util.concurrent.ExecutionException: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/file?limit=10 from pid=13290, uid=10084 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
10-15 01:11:36.802 13290 13341 E b       : 	at java.util.concurrent.FutureTask.report(FutureTask.java:94)
10-15 01:11:36.802 13290 13341 E b       : 	at java.util.concurrent.FutureTask.get(FutureTask.java:164)
10-15 01:11:36.802 13290 13341 E b       : 	at com.instagram.common.n.b.f(GalleryLoaderCallable.java:96)
10-15 01:11:36.802 13290 13341 E b       : 	at com.instagram.common.n.b.call(GalleryLoaderCallable.java:24)
10-15 01:11:36.802 13290 13341 E b       : 	at com.instagram.common.ae.c.run(ChainableTask.java:185)
10-15 01:11:36.802 13290 13341 E b       : 	at com.instagram.common.ae.j.a(ListenableTask.java:61)
10-15 01:11:36.802 13290 13341 E b       : 	at com.instagram.common.ae.g.run(ExecutorScheduler.java:38)
10-15 01:11:36.802 13290 13341 E b       : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-15 01:11:36.802 13290 13341 E b       : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-15 01:11:36.802 13290 13341 E b       : 	at java.lang.Thread.run(Thread.java:818)
10-15 01:11:36.802 13290 13341 E b       : 	at com.instagram.common.ah.c.c.run(IgThread.java:41)
10-15 01:11:36.802 13290 13341 E b       : Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/file?limit=10 from pid=13290, uid=10084 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
10-15 01:11:36.802 13290 13341 E b       : 	at android.os.Parcel.readException(Parcel.java:1599)
10-15 01:11:36.802 13290 13341 E b       : 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
10-15 01:11:36.802 13290 13341 E b       : 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
10-15 01:11:36.802 13290 13341 E b       : 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
10-15 01:11:36.802 13290 13341 E b       : 	at android.content.ContentResolver.query(ContentResolver.java:491)
10-15 01:11:36.802 13290 13341 E b       : 	at android.content.ContentResolver.query(ContentResolver.java:434)
10-15 01:11:36.802 13290 13341 E b       : 	at com.instagram.common.n.c.a(GalleryLoaderCallable.java:139)
10-15 01:11:36.802 13290 13341 E b       : 	at com.instagram.common.n.c.call(GalleryLoaderCallable.java:121)
10-15 01:11:36.802 13290 13341 E b       : 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-15 01:11:36.802 13290 13341 E b       : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-15 01:11:36.802 13290 13341 E b       : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-15 01:11:36.802 13290 13341 E b       : 	at java.lang.Thread.run(Thread.java:818)
10-15 01:11:36.804 13290 13326 E Surface : getSlotFromBufferLocked: unknown buffer: 0x9e02a7c0
```

In android 6, to access external storage you need to ask additional permission,
I'm not completely understand that new permission model and how you can overcome it so i can't recommend  any fix atm

Thanks!

**Comment by EddyVerbruggen** [comment]
Thanks for the heads-up, I found this article to be relevant: http://metova.com/dev/blog/2015/09/15/android-marshmallow-permissions/

If anyone wants to give it a shot I'd be happy to give write permissions to the repo. Otherwise it may take a while before I get to it.

**Comment by Bnaya** [comment]
Update:
I've opened instagram, click to share image from internal storage and it prompt for permission to access local storage and i granted it.
And now the sharing is back to work with instagram.

I still have problems with other applications that don't ask that permission at all or ones that the user won't prompt for it or until he will.

**Comment by aderbas** [comment]
https://github.com/NativeScript/NativeScript/issues/1434

**Comment by Maheshbhusanoor** [comment]
add this line to config.xml

       <feature name="http://api.phonegap.com/1.0/file" />
