### ISSUE TITLE
Whatsapp image sharing issue on android latest version 2.16.95

### ISSUE THREAD

**Issue by monikaagg** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#617]
I am trying to share image with URL on whats app android .It was working fine on earliest versions but not working with latest version(2.16.95) giving some **file format not supported** issue. Can anybody help me out to track the issue with latest release?

**Comment by wninou** [comment]
same problem :
```
W/ActivityManager: Activity is launching as a new task, so cancelling activity result.
W/Bundle: Key android.intent.extra.STREAM expected ArrayList but value was a android.net.Uri$StringUri.  The default value <null> was returned.
D/OpenGLRenderer: endAllStagingAnimators on 0x9d8f1d80 (RippleDrawable) with handle 0xab1f0580
W/Bundle: Attempt to cast generated internal exception:
                                         java.lang.ClassCastException: android.net.Uri$StringUri cannot be cast to java.util.ArrayList
                                             at android.os.Bundle.getParcelableArrayList(Bundle.java:838)
                                             at android.content.Intent.getParcelableArrayListExtra(Intent.java:5405)
                                             at com.whatsapp.ContactPicker.c(ContactPicker.java:12)
                                             at com.whatsapp.ContactPicker.onCreate(ContactPicker.java:526)
                                             at android.app.Activity.performCreate(Activity.java:6251)
                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                             at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                             at android.os.Looper.loop(Looper.java:148)
                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                             at java.lang.reflect.Method.invoke(Native Method)
                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
...
```
any help ?

**Comment by deryfebriantara** [comment]
same here, it show toast unsuported format. what happened?

**Comment by deryfebriantara** [comment]
after view hours of debugging.. I found that my URL image contain spaces. the solution I just encoded the URL image.

**Comment by engehabahmed** [comment]
Did any one use shareViaWhatsAppToReceiver?
Also shareViaWhatsApp cause faild to open, have any one this issue?
