### ISSUE TITLE
android.os.FileUriExposedException Android SDK > 24 shareViaWhatsApp shareTwitter

### ISSUE THREAD

**Issue by onlydave** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#714]
Sharing an image using shareViaWhatsApp or shareTwitter on android 24+ causes my app to crash, error from logcat bellow. Seem [If your targetSdkVersion is 24 or higher, we have to use FileProvider class to give access to the particular file or folder to make them accessible for other apps.](http://stackoverflow.com/a/38858040/801979)

Doesn't happen using shareWithOptions and selecting whatsapp or twitter from the menu. Text and image both share just fine that way

```
11-24 12:28:32.193 12670 12670 E AndroidRuntime: android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.venueone.sportdec/files/socialsharing-downloads/B1pt19HEMg.png exposed beyond app through ClipData.Item.getUri()
11-24 12:28:32.193 12670 12670 E AndroidRuntime: 	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
11-24 12:28:32.193 12670 12670 E AndroidRuntime: 	at android.net.Uri.checkFileUriExposed(Uri.java:2346)
11-24 12:28:32.193 12670 12670 E AndroidRuntime: 	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:845)
11-24 12:28:32.193 12670 12670 E AndroidRuntime: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:8941)
11-24 12:28:32.193 12670 12670 E AndroidRuntime: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:8926)
11-24 12:28:32.193 12670 12670 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
11-24 12:28:32.193 12670 12670 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4225)
11-24 12:28:32.193 12670 12670 E AndroidRuntime: 	at org.apache.cordova.CordovaActivity.startActivityForResult(CordovaActivity.java:342)
11-24 12:28:32.193 12670 12670 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4183)
11-24 12:28:32.193 12670 12670 E AndroidRuntime: 	at org.apache.cordova.CordovaInterfaceImpl.startActivityForResult(CordovaInterfaceImpl.java:66)
11-24 12:28:32.193 12670 12670 E AndroidRuntime: 	at nl.xservices.plugins.SocialSharing$2$1.run(SocialSharing.java:311)
11-24 12:28:32.193 12670 12670 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
11-24 12:28:32.193 12670 12670 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-24 12:28:32.193 12670 12670 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-24 12:28:32.193 12670 12670 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
11-24 12:28:32.193 12670 12670 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-24 12:28:32.193 12670 12670 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
11-24 12:28:32.193 12670 12670 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

```
Cordova CLI: 6.4.0
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62
```

```
cordova-plugin-x-socialsharing 5.1.3 "SocialSharing"
```

```
ionic platform ls
Installed platforms:
  android 6.1.0
```

**Comment by onlydave** [comment]
adding android-targetSdkVersion of 23 to config.xml gets the shareVia functions working with images again in the meantime
```
<preference name="android-targetSdkVersion" value="23" />
```
