### ISSUE TITLE
Multiple Android dex files for android-support

### ISSUE THREAD

**Issue by JasonTolliver** [EddyVerbruggen/SocialSharing-PhoneGap-Plugin#765]
After installing this plugin, I am still able to actually build the app but I am not able to install it on a device.

I am getting errors regarding multiple dex files for `Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl`.

I have run `gradle -q dependencies` and don't find any other cases of android-support, however I am getting the following errors when attempting an install:

```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:591)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:546)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:528)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)


 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexArmv7Debug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Users/thejasontolliver/Library/Android/sdk/build-tools/24.0.0/dx --dex --no-optimize --output /webroot/company/phonegap/sites-mobile-app/platforms/android/build/intermediates/dex/armv7/debug --input-list=/webroot/company/phonegap/sites-mobile-app/platforms/android/build/intermediates/tmp/dex/armv7/debug/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:591)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:546)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:528)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
  		at com.android.dx.command.dexer.Main.run(Main.java:277)
  		at com.android.dx.command.dexer.Main.main(Main.java:245)
  		at com.android.dx.command.Main.main(Main.java:106)
  	


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by JasonTolliver** [comment]
I found the issue, it appears that the `com.phonegap.plugins.facebookconnect` was including a `support-v13` which was conflicting.  I fixed the issue by simply removing the `compile "com.android.support:support-v4:24.1.1+"` that was added to my `build.gradle` by this plugin.
